// Centralized hugeicons exports.
// All icon names below are verified to exist in @hugeicons/core-free-icons.
// Usage:  import { Icon } from "@/lib/icons";  <Icon name="home" size={20} />

import type * as React from "react";
import { HugeiconsIcon, type IconSvgElement } from "@hugeicons/react";
import {
  Home01Icon, Home02Icon,
  DashboardSquare01Icon, DashboardSquare02Icon,
  Grid02Icon, GridIcon, LayoutGridIcon,
  ShoppingBag01Icon, ShoppingBag02Icon,
  PrinterIcon,
  UserIcon, UserGroupIcon, UserGroup02Icon, UserMultipleIcon, UserMultiple02Icon,
  UserCircleIcon, UserSettings01Icon, UserAdd01Icon, UserEdit01Icon,
  Settings01Icon, Settings02Icon,
  Search01Icon, Search02Icon,
  BellIcon, BellRingIcon, BellOffIcon, BellPlusIcon, BellDotIcon,
  Calendar01Icon, Calendar02Icon, Calendar03Icon, CalendarAdd01Icon, CalendarCheckIcon,
  TruckIcon, TruckDeliveryIcon, TruckReturnIcon,
  Wallet01Icon, Wallet02Icon, Money01Icon, Money02Icon, Coins01Icon, Coins02Icon,
  File01Icon, File02Icon,
  Invoice01Icon, Invoice02Icon, Invoice03Icon, InvoiceIcon,
  CreditCardIcon,
  ReceiptDollarIcon,
  PencilIcon, PencilEdit01Icon, Edit01Icon, Edit02Icon, PaintBoardIcon,
  Wrench01Icon, Wrench02Icon, ToolboxIcon,
  Package01Icon, Package02Icon, PackageAddIcon, BoxesIcon, WarehouseIcon,
  PackageReceive01Icon, PackageSent01Icon, PackageDelivered01Icon,
  Layers01Icon, Layers02Icon,
  Clock01Icon, Clock02Icon, Clock03Icon,
  Key01Icon, Key02Icon, Shield01Icon, Shield02Icon, ShieldKeyIcon,
  Chart01Icon, Chart02Icon, ChartColumnIcon, ChartLineIcon, ChartBarIncreasingIcon, ChartColumnIncreasingIcon, AnalyticsUpIcon, AnalyticsDownIcon, TrendingUpDownIcon,
  Menu01Icon, Menu02Icon, Menu03Icon, Menu04Icon,
  Login01Icon, Logout01Icon, Logout02Icon, Logout03Icon,
  Moon01Icon, Moon02Icon, Sun01Icon, Sun02Icon, Sun03Icon,
  ChevronDownIcon, ChevronUpIcon, ChevronLeftIcon, ChevronRightIcon,
  PlusSignIcon, PlusSignCircleIcon, Add01Icon, AddCircleIcon,
  MinusSignIcon,
  Delete01Icon, Delete02Icon,
  Copy01Icon, Copy02Icon, CopyIcon,
  CheckIcon, CheckmarkCircle01Icon, CheckmarkCircle02Icon, CheckmarkBadge01Icon, Tick01Icon, Tick02Icon,
  InformationCircleIcon, AlertCircleIcon, Alert01Icon, Alert02Icon,  Task01Icon, Task02Icon, TaskAdd01Icon, TaskDone01Icon, CheckListIcon,
  CustomerService01Icon, CustomerService02Icon, CustomerServiceIcon,
  Store01Icon, Store02Icon, Building01Icon, Building02Icon, Building03Icon, Factory01Icon, Factory02Icon,
  MoreHorizontalIcon, MoreVerticalIcon, More01Icon, More02Icon,
  FilterIcon, FilterHorizontalIcon, SlidersHorizontalIcon, SlidersVerticalIcon,
  ArrowRight01Icon, ArrowLeft01Icon, ArrowUp01Icon, ArrowDown01Icon, ArrowUpDownIcon, ArrowLeft02Icon, ArrowRight02Icon,
  SortByDown01Icon, SortByUp01Icon,
  StarIcon, StarOffIcon, StarHalfIcon, Bookmark01Icon, HeartIcon,
  Mail01Icon, Mail02Icon, MailOpen01Icon,
  MapPinIcon, MapPinCheckIcon,
  Globe02Icon, GlobeIcon,
  EyeIcon, EyeOffIcon, ViewIcon, ViewOffIcon,
  Download01Icon, Upload01Icon,
  Refresh01Icon, RefreshIcon, ReloadIcon,
  Loading01Icon, Loading02Icon, Loading03Icon,
  CircleCheckIcon,
  Cancel01Icon, CancelCircleIcon,
  Square01Icon, ExpandIcon, CollapseIcon,
  PercentIcon, Tag01Icon, Tag02Icon, TagsIcon,
  Archive01Icon, Archive02Icon,
  PlayIcon, PlayCircleIcon, PauseCircleIcon,
  Route01Icon, Route02Icon,
  InboxIcon, InboxUnreadIcon,
  LockIcon, LockPasswordIcon, FingerPrintIcon,
  Award01Icon, Award02Icon, Medal01Icon,
  GiftIcon, GiftCardIcon,
  Notification01Icon, Notification02Icon, Notification03Icon,
  DocumentValidationIcon,
} from "@hugeicons/core-free-icons";

export const icons = {
  home: Home01Icon,
  home2: Home02Icon,
  dashboard: DashboardSquare01Icon,
  dashboard2: DashboardSquare02Icon,
  grid: Grid02Icon,
  grid2: LayoutGridIcon,
  orders: ShoppingBag01Icon,
  orders2: ShoppingBag02Icon,
  print: PrinterIcon,
  printer: PrinterIcon,
  user: UserIcon,
  users: UserGroupIcon,
  userGroup: UserGroupIcon,
  userGroup2: UserGroup02Icon,
  userMultiple: UserMultipleIcon,
  customers: UserMultiple02Icon,
  userCircle: UserCircleIcon,
  userSettings: UserSettings01Icon,
  userAdd: UserAdd01Icon,
  userEdit: UserEdit01Icon,
  suppliers: TruckIcon,
  truck: TruckIcon,
  truckDelivery: TruckDeliveryIcon,
  wallet: Wallet01Icon,
  money: Money01Icon,
  coins: Coins01Icon,
  file: File01Icon,
  file2: File02Icon,
  document: DocumentValidationIcon,
  invoice: Invoice01Icon,
  invoice2: Invoice02Icon,
  invoice3: Invoice03Icon,
  receipt: ReceiptDollarIcon,
  creditCard: CreditCardIcon,
  design: PaintBoardIcon,
  pencil: PencilIcon,
  edit: Edit01Icon,
  edit2: Edit02Icon,
  tool: Wrench01Icon,
  wrench: Wrench01Icon,
  toolbox: ToolboxIcon,
  gear: Settings01Icon,
  settings: Settings01Icon,
  settings2: Settings02Icon,
  package: Package01Icon,
  package2: Package02Icon,
  packageAdd: PackageAddIcon,
  boxes: BoxesIcon,
  warehouse: WarehouseIcon,
  packageReceive: PackageReceive01Icon,
  packageSent: PackageSent01Icon,
  packageDelivered: PackageDelivered01Icon,
  layers: Layers01Icon,
  clock: Clock01Icon,
  clock2: Clock02Icon,
  key: Key01Icon,
  key2: Key02Icon,
  shield: Shield01Icon,
  shieldKey: ShieldKeyIcon,
  chart: Chart01Icon,
  chartColumn: ChartColumnIcon,
  chartLine: ChartLineIcon,
  chartBar: ChartBarIncreasingIcon,
  analytics: AnalyticsUpIcon,
  analyticsDown: AnalyticsDownIcon,
  trending: TrendingUpDownIcon,
  menu: Menu01Icon,
  menu2: Menu02Icon,
  menu3: Menu03Icon,
  login: Login01Icon,
  logout: Logout01Icon,
  logout2: Logout02Icon,
  moon: Moon02Icon,
  sun: Sun02Icon,
  chevronDown: ChevronDownIcon,
  chevronUp: ChevronUpIcon,
  chevronLeft: ChevronLeftIcon,
  chevronRight: ChevronRightIcon,
  plus: PlusSignIcon,
  plusCircle: PlusSignCircleIcon,
  add: Add01Icon,
  addCircle: AddCircleIcon,
  minus: MinusSignIcon,
  trash: Delete01Icon,
  trash2: Delete02Icon,
  delete: Delete01Icon,
  copy: Copy01Icon,
  copy2: Copy02Icon,
  check: CheckIcon,
  checkCircle: CheckmarkCircle01Icon,
  checkCircle2: CheckmarkCircle02Icon,
  checkBadge: CheckmarkBadge01Icon,
  tick: Tick01Icon,
  tick2: Tick02Icon,
  info: InformationCircleIcon,
  alert: AlertCircleIcon,
  alertTriangle: Alert01Icon,
  alert2: Alert02Icon,
  task: Task01Icon,
  taskAdd: TaskAdd01Icon,
  taskDone: TaskDone01Icon,
  checkList: CheckListIcon,
  customerService: CustomerService01Icon,
  store: Store01Icon,
  store2: Store02Icon,
  building: Building01Icon,
  building2: Building02Icon,
  factory: Factory01Icon,
  moreHorizontal: MoreHorizontalIcon,
  moreVertical: MoreVerticalIcon,
  more: More01Icon,
  filter: FilterIcon,
  filterHorizontal: FilterHorizontalIcon,
  sliders: SlidersHorizontalIcon,
  slidersVertical: SlidersVerticalIcon,
  arrowRight: ArrowRight01Icon,
  arrowLeft: ArrowLeft01Icon,
  arrowUp: ArrowUp01Icon,
  arrowDown: ArrowDown01Icon,
  arrowUpDown: ArrowUpDownIcon,
  sortDown: SortByDown01Icon,
  sortUp: SortByUp01Icon,
  star: StarIcon,
  starOff: StarOffIcon,
  starHalf: StarHalfIcon,
  bookmark: Bookmark01Icon,
  heart: HeartIcon,
  mail: Mail01Icon,
  mail2: Mail02Icon,
  mailOpen: MailOpen01Icon,
  mapPin: MapPinIcon,
  mapPinCheck: MapPinCheckIcon,
  globe: Globe02Icon,
  globe2: GlobeIcon,
  eye: EyeIcon,
  eyeOff: EyeOffIcon,
  view: ViewIcon,
  viewOff: ViewOffIcon,
  download: Download01Icon,
  upload: Upload01Icon,
  refresh: Refresh01Icon,
  reload: ReloadIcon,
  spinner: Loading03Icon,
  loading: Loading01Icon,
  loading2: Loading02Icon,
  circleAlert: AlertCircleIcon,
  circleCheck: CircleCheckIcon,
  cancel: Cancel01Icon,
  cancelCircle: CancelCircleIcon,
  square: Square01Icon,
  expand: ExpandIcon,
  collapse: CollapseIcon,
  tag: Tag01Icon,
  tags: TagsIcon,
  percent: PercentIcon,
  calendar: Calendar03Icon,
  calendar2: Calendar02Icon,
  calendarAdd: CalendarAdd01Icon,
  calendarCheck: CalendarCheckIcon,
  archive: Archive01Icon,
  archive2: Archive02Icon,
  pause: PauseCircleIcon,
  play: PlayIcon,
  playCircle: PlayCircleIcon,
  route: Route01Icon,
  inbox: InboxIcon,
  inboxUnread: InboxUnreadIcon,
  lock: LockIcon,
  lockPassword: LockPasswordIcon,
  fingerprint: FingerPrintIcon,
  bell: BellIcon,
  bellRing: BellRingIcon,
  bellOff: BellOffIcon,
  bellPlus: BellPlusIcon,
  notification: Notification03Icon,
  notification2: Notification01Icon,
  award: Award01Icon,
  medal: Medal01Icon,
  gift: GiftIcon,
  giftCard: GiftCardIcon,
  store3: Store02Icon,
  search: Search01Icon,
  searchList: Search02Icon,
} satisfies Record<string, IconSvgElement>;

export type IconName = keyof typeof icons;

export { HugeiconsIcon };
export type { IconSvgElement };

export function Icon({
  name,
  size = 20,
  className,
  strokeWidth,
  ...rest
}: {
  name: IconName;
  size?: number | string;
  className?: string;
  strokeWidth?: number;
} & Omit<React.ComponentProps<typeof HugeiconsIcon>, "icon">) {
  const icon = icons[name];
  if (!icon) return null;
  return (
    <HugeiconsIcon
      icon={icon}
      size={size}
      className={className}
      strokeWidth={strokeWidth}
      {...rest}
    />
  );
}
