// PHASE 27 — build src/lib/i18n/dict-en.ts + dict-fa.ts from translations.json
// + extra-translations.json (manual additions/overrides).
//
//   dict-en: natural key (Persian source) → English
//   dict-fa: reverse map (English → Persian) so NEW English-authored strings
//            render Persian in fa mode (see I18N_RULES.md)
//
// Run AFTER translate.mjs completes:  node scripts/i18n/build-dicts.mjs

import fs from "node:fs";
import path from "node:path";

const DIR = "/home/z/my-project/scripts/i18n";
const SRC = "/home/z/my-project/src/lib/i18n";
const PERSIAN_RE = /[\u0600-\u06FF\u0750-\u077F\uFB50-\uFDFF\uFE70-\uFEFF]/;

const main = JSON.parse(fs.readFileSync(path.join(DIR, "translations.json"), "utf8"));
let extra = {};
const extraPath = path.join(DIR, "extra-translations.json");
if (fs.existsSync(extraPath)) {
  extra = JSON.parse(fs.readFileSync(extraPath, "utf8"));
}
const merged = { ...main, ...extra };

const entries = Object.entries(merged).filter(([k, v]) => typeof v === "string" && v.trim());

// sanity report
const noPersianKey = entries.filter(([k]) => !PERSIAN_RE.test(k));
const persianValue = entries.filter(([, v]) => PERSIAN_RE.test(v));
console.log(`entries: ${entries.length} (main ${Object.keys(main).length} + extra ${Object.keys(extra).length})`);
if (noPersianKey.length) console.log(`NOTE: ${noPersianKey.length} English-authored keys (fa dict entries)`);
if (persianValue.length) {
  console.warn(`WARN: ${persianValue.length} values still contain Persian script:`);
  for (const [k, v] of persianValue.slice(0, 10)) console.warn(`   ${k.slice(0, 40)} -> ${v.slice(0, 50)}`);
}

function emitMap(name, entriesArr, comment) {
  const lines = entriesArr.map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`);
  return `// ${comment}\n// AUTO-GENERATED by scripts/i18n/build-dicts.mjs — do not edit by hand;\n// regenerate instead. Manual additions go to scripts/i18n/extra-translations.json.\n\nexport const ${name}: Record<string, string> = {\n${lines.join("\n")}\n};\n`;
}

// dict-en: only keys that contain Persian (legacy natural keys)
const enEntries = entries.filter(([k]) => PERSIAN_RE.test(k));
fs.writeFileSync(
  path.join(SRC, "dict-en.ts"),
  emitMap("DICT_EN", enEntries, "PHASE 27 — Persian (natural key) → English. English is the default UI language."),
  "utf8"
);

// dict-fa: reverse map (English → Persian). English-authored keys pass through
// directly (they are already the fa-dict direction). Persian keys whose English
// value collides: first wins (logged).
const faMap = new Map();
const collisions = [];
for (const [k, v] of entries) {
  if (!PERSIAN_RE.test(k)) {
    faMap.set(k, v); // English key → Persian value (extra entries authored in English)
  } else if (!faMap.has(v)) {
    faMap.set(v, k); // reverse: English value → Persian key
  } else {
    collisions.push(v);
  }
}
fs.writeFileSync(
  path.join(SRC, "dict-fa.ts"),
  emitMap("DICT_FA", [...faMap.entries()], "PHASE 27 — English → Persian (reverse map for fa mode)."),
  "utf8"
);

console.log(`dict-en entries: ${enEntries.length}`);
console.log(`dict-fa entries: ${faMap.size} (reverse collisions skipped: ${collisions.length})`);
